name: Benchmark-Linux

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

concurrency: benchmark_linux

jobs:
  bench:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Benchmark
      run: dotnet run --project "BitFaster.Caching.Benchmarks" -f net6.0 -c Release --filter '*'
    - name: Publish Results
      uses: actions/upload-artifact@v3
      with:
        name: Benchmark Artifacts
        path: BenchmarkDotNet.Artifacts